### ISSUE TITLE
Python 3 and dependences

### ISSUE THREAD

**Issue by philipyoung9561** [ClementiGroup/pyODEM#2]
Because the latest version of PyEMMA only support python 3 now, we have to use this package and all its dependences in python 3. There's a command called '2to3', which can automatically translate python 2 codes into python 3. This is necessary for all the packages, because the syntax of import is changed. 
Moreover, I've know found a bug in Alex's simulation package, namely in '/simulation/calc/tram/util.py', when defining class SbmEnergyFeature(CustomFeature), according to the latest version of PyEMMA, '__serialize_version = 0' needs to be added at first. The details can be found in 'pyemma/_base/serialization/serialization.py'

**Comment by ajkluber** [comment]
@philipyoung9561 and I just talked in person, so I will add further context. Wangfei was getting an import error when trying to run the notebook in example_2, the import error was coming from my `simulation` package which is used to write mdp files. I went ahead and removed the subpackage `simulation.calc` that was causing the original import error. However this ticket is still relevant for discussing python 3 support in general. 

Updating the code for python 3 is not difficult (mostly print statements) and when I checked recently almost all third-party python packages of interest support python 3, so that is the way I am going to go with all my own code. @TensorDuck, thoughts?

**Comment by TensorDuck** [comment]
It definitely seems like we're at the point where we need to jump to Python 3. This is mainly because of our heavy integration with PyEMMA. It is semi-trivial to re-factor code to Python 3, however there are a number of differences that might cause problems during the conversion, two examples immediately come to mind:

1. `range()` always returns an `iterator` not a `list` which would ruin any checks you have for `list` in your code.
2. Integer math is different, Python 2: `5/2=2`, Python 3: `5/2=2.5` which could have implications in situations you expected the integer to automatically round down. 

There are probably other minor bugs we will encounter. If we do this, best way to proceed would be to merge the latest changes from the development branches i.e. `test_nonbonded` and then start a new branch where we begin the refactor and add unit-tests. I am rather busy right now until the end of February, but @philipyoung9561 you are welcome to start without me.

**Comment by philipyoung9561** [comment]
I'm going through the second example of pyodem under python 3. I'll try to fix the issues caused by compatibility (the one mentioned above so far), and I'll let you know if I have any update.
